name: Deploy CDK to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'CDK action to perform (deploy or destroy)'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - destroy
      deploy_env:
        description: 'Environment to Deploy (e.g: dev, test, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod


permissions:
  id-token: write       # required for OIDC
  contents: read        # required to read the repo

jobs:
  cdk-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:      
        working-directory: genai

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials from IAM Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install CDK Dependencies
        run: |
          npm ci
          npm install -g aws-cdk

      - name: CDK Bootstrapping (if needed)
        run: cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/${{ secrets.AWS_REGION }}

      - name: CDK Synth
        run: |
          DEPLOY_ENV=${{ github.event.inputs.deploy_env }} npx cdk synth

      - name: CDK Deploy or Destroy
        run: |
          if [ "${{ github.event.inputs.action }}" == "deploy" ]; then
            DEPLOY_ENV=${{ github.event.inputs.deploy_env }} npx cdk deploy --require-approval never
          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            DEPLOY_ENV=${{ github.event.inputs.deploy_env }} npx cdk destroy --require-approval never
          else
            echo "Invalid action: ${{ github.event.inputs.action }}"
            exit 1
          fi
